apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYXJyb3c5MjUwMCIsInBhc3N3b3JkIjoiZ2hwX0xvQTQ0c05pdVdyVmdNWDgxYk9sbmJodFdNWW1HRDFocGhuMiIsImF1dGgiOiJZWEp5YjNjNU1qVXdNRHBuYUhCZlRHOUJORFJ6VG1sMVYzSldaMDFZT0RGaVQyeHVZbWgwVjAxWmJVZEVNV2h3YUc0eSJ9fX0=
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
